### ISSUE TITLE
entities and interactors are not cohesive packages

### ISSUE THREAD

**Issue by radams78** [ArvidHammarlund/TDA553-lab1#12]
It is not good practice to put all entities into one package, all interactors into another etc. Classes should be placed together in packages if they use each other. So in one package I expect to see entities, interactors and adapters that depend on each other, with a few of these made public as the interface to the package for the rest of the system.

**Comment by ArvidHammarlund** [comment]
I've revised the directory structure. I've tried to make it conform more to cohesion and functionality this time. 

I have a question, though: is it bad practice to use folders to separate the components of the logic, e.g. cars and trucks, in order to make it more understandable for humans, or should you only consider cohesion?

.
├── java
│   └── lab
│       ├── Application.java
│       ├── Model.java
│       ├── ModelObserver.java
│       ├── controllers
│       │   ├── BrakeButton.java
│       │   ├── Button.java
│       │   ├── GasButton.java
│       │   ├── LiftDownButton.java
│       │   ├── LiftUpButton.java
│       │   ├── Spinner.java
│       │   ├── StartButton.java
│       │   ├── StopButton.java
│       │   ├── TurboOffButton.java
│       │   └── TurboOnButton.java
│       ├── entities
│       │   ├── Body.java
│       │   ├── Direction.java
│       │   ├── Engine.java
│       │   ├── Movable.java
│       │   ├── Tools.java
│       │   ├── Vehicle.java
│       │   ├── cars
│       │   │   ├── Car.java
│       │   │   ├── Coupe.java
│       │   │   ├── Saab95.java
│       │   │   ├── Sedan.java
│       │   │   ├── TrimEngine.java
│       │   │   ├── TurboEngine.java
│       │   │   ├── Turboable.java
│       │   │   └── Volvo240.java
│       │   ├── firms
│       │   │   └── RepairShop.java
│       │   └── trucks
│       │       ├── Flatbed.java
│       │       ├── Loadable.java
│       │       ├── Platform.java
│       │       ├── Raisable.java
│       │       ├── Scania.java
│       │       ├── Transporter.java
│       │       ├── Truck.java
│       │       └── TruckEngine.java
│       └── views
│           ├── ControllPanel.java
│           ├── DrawRacetrack.java
│           ├── Frame.java
│           ├── GasPanel.java
│           ├── PictureDownloader.java
│           └── SpeedDisplay.java
└── resources
    ├── Saab95.jpg
    ├── Scania.jpg
    ├── Volvo240.jpg
    └── pics
        ├── Saab95.jpg
        ├── Scania.jpg
        └── Volvo240.jpg
